// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLLAg3ZsPJtBaHV6b66SKR0tWto2znyc',
    appId: '1:532974929194:web:32f0d9181f2125b7b24a53',
    messagingSenderId: '532974929194',
    projectId: 'time-table-5148b',
    authDomain: 'time-table-5148b.firebaseapp.com',
    storageBucket: 'time-table-5148b.firebasestorage.app',
    measurementId: 'G-8D9KP62C10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIC5wIN6CL4NYRWd0MiNGpEOJg1sy80VI',
    appId: '1:532974929194:android:9936ed729c1a271bb24a53',
    messagingSenderId: '532974929194',
    projectId: 'time-table-5148b',
    storageBucket: 'time-table-5148b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKRDDQBubpoV1miiWkpWI3Qxz-VCXOb4',
    appId: '1:532974929194:ios:c8a7895a1aa0f2b2b24a53',
    messagingSenderId: '532974929194',
    projectId: 'time-table-5148b',
    storageBucket: 'time-table-5148b.firebasestorage.app',
    iosBundleId: 'com.example.timetableSceduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApKRDDQBubpoV1miiWkpWI3Qxz-VCXOb4',
    appId: '1:532974929194:ios:c8a7895a1aa0f2b2b24a53',
    messagingSenderId: '532974929194',
    projectId: 'time-table-5148b',
    storageBucket: 'time-table-5148b.firebasestorage.app',
    iosBundleId: 'com.example.timetableSceduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLLAg3ZsPJtBaHV6b66SKR0tWto2znyc',
    appId: '1:532974929194:web:0333351d44276969b24a53',
    messagingSenderId: '532974929194',
    projectId: 'time-table-5148b',
    authDomain: 'time-table-5148b.firebaseapp.com',
    storageBucket: 'time-table-5148b.firebasestorage.app',
    measurementId: 'G-GKKC7F3GXV',
  );
}